### PR TITLE
Add config.schema.json for UI-X settings support

### PR DESCRIPTION
**Pull request by cap10morgan**
As documented here: https://github.com/oznu/homebridge-config-ui-x/wiki/Developers%3A-Plugin-Settings-GUI

### CODE REVIEW

**Comment by DMBlakeley** [comment]
config.schema.json as proposed is not complete. "armingModes" is not included. Optional elements "authTimeoutMinutes" and "pollTimeoutSeconds" are also not included.

I am looking at implementing these elements.

**Comment by cap10morgan** [comment]
@DMBlakeley Yeah, I didn't intend to add all of them right away. You can still add them the usual way even with this. But feel free to add them yourself. It shouldn't block merging this, though, IMO.

**Comment by DMBlakeley** [comment]
I recently submitted a config.schema.json implementation for `homebridge-awair` for consideration. When I did the Awair implementation, the interface picked up config values that already existed in config.json.  This was not the case with the `homebridge-node-alarm-dot-com` version.

Poking around a bit I found that "platform" in the config.json file needed to be `"platform": "AlarmDotCom"` rather than "platform": "Alarmdotcom" as stated in the `README.md` file. This change should probably be made also.

Also, can you clarify if  Arming Modes are required or optional?

**Comment by DMBlakeley** [comment]
Further update ...

"platform" in the config.json file and "pluginAlias" in the schema file need to match. As the README.md file states "Alarmdotcom" just change "pluinAlias" to match and all is good.

**Comment by cap10morgan** [comment]
> just change "pluinAlias" to match and all is good

Done. Did that end up being the only change needed?

**Comment by DMBlakeley** [comment]
Yes, for the required parameters to work.

**Comment by mkormendy** [comment]
I'm not ready to pull this into the main repo yet, I am waiting for one of the people I am testing the lights configuration to get back from being out of town and then I can test the changes I have made to fix that issue first before adding this. Plus there are a couple of other changes that need to be grouped with this implementation so it will be verified as working with Config UI X.

**Pull request merged**
